extends: default

rules:
  document-start: disable
  truthy:
    check-keys: false
    allowed-values:
      - 'true'
      - 'false'
  empty-lines:
    max: 1
  hyphens:
    max-spaces-after: 1
  indentation:
    spaces: 2

ignore: |
  node_modules/
