name: github pages
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    container: node:12.16.3-slim
    steps:
      - uses: actions/checkout@master

      - name: install packages
        run: npm install
      
      - name: build
        run: npm run prod
      
      - name: publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./assets